# Configuration file for Road Car Traffic Counter / Detection System

# Example YAML config
camera:
  type: "video"  # Options: "video", "camera"
  source: "test_videos/test video_1.mp4"  # Options: 0 (for webcam) or video file path, e.g.: "test_videos/test video_1.mp4"
  #source: 0  # Options: 0 (for webcam) or video file path, e.g.: "test_videos/test video_1.mp4"
  resolution: [1280, 720]

detection:
  model: yolov11
  confidence_threshold: 0.5

counting:
  line_position: [600, 400]
  direction: 'vertical'

logging:
  output_csv: 'traffic_log.csv'
  enable_encryption: true

uiux:
  dashboard_port: 8050
  theme: 'bootstrap'
